# Generated by Django 3.1.7 on 2021-07-18 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('text', models.TextField(blank=True, max_length=500, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['completed'],
            },
        ),
    ]
